//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllforCamping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones
    {
        public int Id { get; set; }
        public Nullable<int> usuario { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public int telefono { get; set; }
        public int cp { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
