//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllforCamping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string ap_pat { get; set; }
        public string ap_mat { get; set; }
        public string email { get; set; }
        public int telefono { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string calle { get; set; }
        public Nullable<int> numext { get; set; }
        public string colonia { get; set; }
    }
}
