//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllforCamping
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int Id { get; set; }
        public Nullable<int> proveedor { get; set; }
        public Nullable<int> producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> total { get; set; }
        public string status { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
