//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllforCamping
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public int Id { get; set; }
        public int producto { get; set; }
        public int venta { get; set; }
        public int cantidad { get; set; }
        public int subtotal { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual ventas ventas { get; set; }
    }
}
