//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllforCamping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ventas()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int Id { get; set; }
        public System.DateTime fecha { get; set; }
        public double total { get; set; }
        public int usuario { get; set; }
        public string pago { get; set; }
        public string guia { get; set; }
        public string fecha_envio { get; set; }
        public string fecha_entrega { get; set; }
        public int paqueteria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual paqueterias paqueterias { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
